In [ ]:
import pandas as pd

df = pd.read_excel('data_preprocess.xlsx')

df_modi = df.drop(7)
df_modi.dropna(inplace=True)
df_modi.loc[6, 'age'] = 18

print(df_modi.iloc[6, 3])

Doctor

In [16]:
df_col1 = df_modi['name']
print(df_col1)
print(type(df_modi))

df_col2 = df_modi[['age', 'job']]
print(df_col2)
print(type(df_col2))

0     Jackson
1       Lucas
3     Abigail
4       James
5    Benjamin
6     William
9       Henry
Name: name, dtype: str
<class 'pandas.DataFrame'>
    age            job
0  27.0          Sales
1  15.0   Student(mid)
3  24.0        Waiters
4  28.0        Analyst
5  34.0       Cashiers
6  18.0  Student(high)
9  43.0         Doctor
<class 'pandas.DataFrame'>

In [20]:
# print(df_modi.loc[3])
# print(df_modi.iloc[3])

df_modi['age'] = df_modi['age'].astype(int)
df_modi

       name  age   address            job
0   Jackson   27   Gangwon          Sales
1     Lucas   15     Seoul   Student(mid)
3   Abigail   24     Busan        Waiters
4     James   28      Jeju        Analyst
5  Benjamin   34  Gyeonggi       Cashiers
6   William   18     Ulsan  Student(high)
9     Henry   43     Daegu         Doctor

In [24]:
df_modi.sort_values(by=['name'], ascending=True, inplace=True)
df_modi

       name  age   address            job
3   Abigail   24     Busan        Waiters
5  Benjamin   34  Gyeonggi       Cashiers
9     Henry   43     Daegu         Doctor
0   Jackson   27   Gangwon          Sales
4     James   28      Jeju        Analyst
1     Lucas   15     Seoul   Student(mid)
6   William   18     Ulsan  Student(high)